console.log('Segunda Parte de arreglos');
let arreglo=[50,80,72,60,96];
console.log('-------------------------');
console.log('Antes');
console.log(arreglo);
arreglo.splice(2,1);
console.log('Despues');
console.log(arreglo);
console.log('-------------------------');
let arreglo2=[50,80,72,60,96];
console.log('Antes');
console.log(arreglo2);
arreglo.splice(2,1,99);
console.log('Despues');
console.log(arreglo2);
console.log('-------------------------');
let arreglo3=[50,80,72,60,96];
console.log('Antes');
console.log(arreglo3);
arreglo.splice(2,0,99);
console.log('Despues');
console.log(arreglo3);